### ISSUE TITLE
Deutsch -> Japanisch Suche

### ISSUE THREAD

**Issue by martinfinke** [makigumo/wadoku-mac-dic#14]
Danke für das Dictionary! Ich benutze es sehr oft am Mac.

Wäre vielleicht auch eine Suche von Deutsch nach Japanisch möglich? Wenn ich z.B. auf www.wadoku.de `Haus` eingebe, zeigt es die japanischen Übersetzungen dafür. (Leider in einer seltsamen Reihenfolge, zum Beispiel kommt 家 erst nach ca. 20 viel weniger geläufigen Wörtern, aber das ist ein anderes Problem)

**Comment by makigumo** [comment]
Ich fürchte, da lässt sich so einfach leider keine zufriedenstellende Lösung finden. Mit einigem Aufwand ließe sich eine "Deutsch-Suche" mit einbauen. Diese würde aber die gleichen Probleme wie auf www.wadoku.de haben und somit zu, für die meisten Nutzer, eher verwirrenden oder sogar irreführenden Suchergebnissen führen. Was dann zu allen möglichen anderen Problemen führen kann.

Zur Referenz mal kurz, was das [Wiki](https://www.wadoku.de/wiki/pages/viewpage.action?pageId=1802) dazu zu sagen hat.

> ### Was ist Wadoku?
> Wadoku ist ein von Ulrich Apel in langjähriger Arbeit konzipiertes und aufgebautes japanisch-deutsches Wörterbuch ([Wörterbuch Lizenz](https://www.wadoku.de/wiki/pages/viewpage.action?pageId=357)). Das heißt, es ist für Übersetzungen aus dem Japanischen ins Deutsche konzipiert. Der Webseite http://www.wadoku.de/ liegt dieses Wörterbuch zugrunde.

> ### Was ist Wadoku nicht?
> Wadoku ist kein deutsch-japanisches Wörterbuch. Das heißt, es ist nicht für Übersetzungen aus dem Deutschen ins Japanische konzipiert. Es gibt Arbeiten an einem deutsch-japanischen Wörterbuch, wenn dieses benutzbar wird, wird diese Suchmöglichkeit aus dem Wadoku entfernt.

> Es gibt diese Suchrichtung auf der Webseite trotzdem, doch die Ergebnisse sind dementsprechend oft suboptimal und mit Vorsicht zu genießen.
